spring:
  application:
    name: boot-sample

server:
  port: 8081

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  metrics:
    tags:
      application: boot-sample
  endpoint:
    health:
      show-details: always